export const IPC_CHANNELS = {
  LAUNCH_GAME: "launch-game",
  START_RELAY_TUNNEL: "start-relay-tunnel",
  START_RELAY_TUNNEL_V2: "start-relay-tunnel-v2",
  KILL_RETROARCH: "kill-retroarch",
  START_MITM_LOCAL: "start-mitm-local",
  STOP_MITM_LOCAL: "stop-mitm-local",
  SAVE_RELAY_URL: "save-relay-url",
  GET_RELAY_URL: "get-relay-url",
  GET_NAKAMA_SERVER: "get-nakama-server",
  SET_NAKAMA_SERVER: "set-nakama-server",
  CHECK_NAKAMA_HEALTH: "check-nakama-health",
  GET_TAILSCALE_IP: "get-tailscale-ip",
  GET_LAN_IP: "get-lan-ip",
  TAILSCALE_HOST: "tailscale-host",
  TAILSCALE_GUEST: "tailscale-guest",
  STOP_TAILSCALE: "stop-tailscale",
  OPEN_FIREWALL_PORT: "open-firewall-port",
  CHECK_PEER_CONNECTIVITY: "check-peer-connectivity",
  READ_NETPLAY_CONFIG: "read-netplay-config",
  WRITE_NETPLAY_CONFIG: "write-netplay-config",
  RESTORE_NETPLAY_CONFIG: "restore-netplay-config",
  GET_STATUS: "get-status",
  GET_METRICS: "get-metrics",
  VALIDATE_DEPENDENCIES: "validate-dependencies",
  ASSERT_PORT_FREE: "assert-port-free",
  GET_RELAY_CONFIG: "get-relay-config",
  SET_RELAY_CONFIG: "set-relay-config",
  CLEAR_RELAY_CONFIG: "clear-relay-config",
  GGPO_LAUNCH: "ggpo-launch",
  GGPO_KILL: "ggpo-kill",
  GGPO_LAUNCH_LOCAL: "ggpo-launch-local",
  P2P_HOST: "p2p-host",
  P2P_GUEST: "p2p-guest",
  P2P_DISCONNECT: "p2p-disconnect",
  P2P_CANDIDATE_FILE: "p2p-candidate-file",
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]

export const IPC_WHITELIST: ReadonlySet<string> = new Set(Object.values(IPC_CHANNELS))
